# ===================================================================
# 실험을 위한 정적 파라미터 (Static Parameters)
# ===================================================================
static:
  # 데이터셋 관련 설정
  data:
    n_samples: 1000
    n_features: 5
    noise: 0.1
    train_split: 0.8

  # 모델 아키텍처 관련 설정
  model:
    input_dim: 5
    output_dim: 1

  # Optuna Study 관련 설정
  study:
    study_name: "general_optimization_framework"
    db_path: "./optuna_study.db"
    n_trials: 50
    # 최적화할 평가지표의 이름을 명시합니다.
    # 이 이름은 ExperimentHandler의 get_metrics()가 반환하는 dict의 key와 일치해야 합니다.
    metric_to_optimize: "val_mse"
    direction: "minimize" # 'minimize' 또는 'maximize'

  # 실행 환경 설정
  device: "cpu"

# ===================================================================
# Optuna를 통해 최적화할 하이퍼파라미터 (Optimization Hyperparameters)
# ===================================================================
optimize:
  # 학습 관련 하이퍼파라미터
  training:
    lr:
      type: "float"
      low: 1.0e-4
      high: 1.0e-1
      log: true
    batch_size:
      type: "categorical"
      choices: [16, 32, 64, 128]
    max_epochs:
      type: "int"
      low: 5
      high: 30

  # 옵티마이저 관련 하이퍼파라미터
  optimizer:
    optimizer_name:
      type: "categorical"
      choices: ["Adam", "RMSprop", "SGD"]
    # SGD 옵티마이저를 선택했을 때만 사용될 파라미터
    sgd_momentum:
      type: "float"
      low: 0.8
      high: 0.99
      log: false
